apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapping
  labels:
    app: mapping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mapping
  template:
    metadata:
      labels:
        app: mapping
    spec:
      containers:
      - name: mapping
        image: kpmgacr.azurecr.io/nginx:#{Build.BuildId}#
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: mapping-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: mapping
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
          app: mapping
